# Generated by Django 2.1.2 on 2020-06-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200615_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customjobinformations',
            name='Comp_Data',
            field=models.CharField(editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='customjobinformations',
            name='Comp_Seq',
            field=models.CharField(editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='customjobinformations',
            name='HtmlData',
            field=models.TextField(editable=False),
        ),
    ]
