# Generated by Django 2.1.2 on 2020-06-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_dashboard_history_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_history_logs',
            name='JobType',
            field=models.CharField(default='CustomJobs', max_length=800),
        ),
    ]
